# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

executors:
  node:
    docker:
      - image: node:lts-alpine
    resource_class: small

workflows:
  generate-release:
    executor:
      name: node
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Install dependencies
          command: apk add --no-cache git
      - run:
          command: npm run generate-release